development:
  adapter: postgresql
  encoding: unicode
  database: addemotion_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: addemotion_test
  pool: 5
  username: addemotion
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: addemotion_production
  pool: 5
  username: addemotion
  password:
